url: https://s1.demo.opensourcecms.com/wordpress/wp-admin/
browser: chrome
username: opensourcecms
password: opensourcecms

login_title: Log In ‹ Inspe — WordPress
dashboard_title: Dashboard ‹ Inspe — WordPress

explicit_timeout: 10s

#chrome_options
chrome_options:
#  - --headless
  - --disable-gpu