url: https://s1.demo.opensourcecms.com/wordpress/wp-admin/
server_url: https://reqres.in
browser: chrome
username: opensourcecms
password: opensourcecms

login_title: Log In ‹ opensourcecms — WordPress
dashboard_title: Dashboard ‹ opensourcecms — WordPress

explicit_timeout: 10s

#chrome_options
chrome_options:
#  - --headless
  - --disable-gpu